CREATE DATABASE asm2;
USE asm2;
CREATE TABLE admin (
  username varchar(255) NOT NULL,
  password varchar(255) DEFAULT NULL,
  init varchar(255) DEFAULT '0',
  createAt datetime DEFAULT NULL,
  updateAt datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Đang đổ dữ liệu cho bảng admin
--

INSERT INTO admin (username, password, init, createAt, updateAt) VALUES
('admin', '$2a$04$c.51Eckp.p1nu1l0uwDghuZw93su/twoBn.X7CNSeZO/rhfjuU6HK', '0', '2023-11-17 21:21:21', '2023-11-17 21:21:21');
-- password: L05_Group2

CREATE TABLE CumNha (
    TenCN VARCHAR(20) PRIMARY KEY,
    SoToa INT NOT NULL,
    ViTri VARCHAR(20) NOT NULL,
    SucChua INT NOT NULL,
    SoLuongCSVC INT NOT NULL
);

CREATE TABLE ToaNha (
    TenTN VARCHAR(20) PRIMARY KEY,
    SoPhong INT NOT NULL,
    SucChua INT NOT NULL,
    SoTang INT NOT NULL,
    LoaiTN CHAR CHECK (LoaiTN IN ('Nam', 'Nữ')),
    TenCN VARCHAR(20) NOT NULL,
    CONSTRAINT FK_TenCN FOREIGN KEY (TenCN) REFERENCES CumNha(TenCN)
);

CREATE TABLE Phong (
	TenTN VARCHAR(20),
    SoPhong INT,
    PRIMARY KEY (TenTN, SoPhong),
    LoaiPhong ENUM('DV', 'KDV'),
    SucChua INT NOT NULL,
    CONSTRAINT FK_TenTN FOREIGN KEY (TenTN) REFERENCES ToaNha(TenTN),
    CONSTRAINT FK_TenTN FOREIGN KEY (TenTN) REFERENCES PhieuDangKyLuuTru(TenTN)
);

CREATE TABLE SinhVien (
	CCCD VARCHAR(12) PRIMARY KEY,
    MSSV VARCHAR(10) NOT NULL,
    GioiTinh CHAR CHECK (GioiTinh IN ('Nam', 'Nữ')),
    Truong VARCHAR(50) NOT NULL,
    Khoa VARCHAR(50) NOT NULL,
    SinhVienNam INT NOT NULL,
    HoVaTen VARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL,
    MaBHYT VARCHAR(20) NOT NULL,
    HoKhau VARCHAR(50) NOT NULL,
    TenTN VARCHAR(20) NOT NULL,
    CONSTRAINT FK_TenTN FOREIGN KEY (TenTN) REFERENCES ToaNha(TenTN),
    SoPhong INT NOT NULL,
    CONSTRAINT FK_SoPhong FOREIGN KEY (SoPhong) REFERENCES ToaNha(SoPhong),
    TP_CCCD VARCHAR(12) NOT NULL,
    UNIQUE (TP_CCCD),
    CONSTRAINT FK_emp_TP_CCCD FOREIGN KEY (TP_CCCD) REFERENCES SinhVien(CCCD)
);

CREATE TABLE SoDienThoaiSV (
	CCCD VARCHAR(12),
    SoDienThoai VARCHAR(10),
    PRIMARY KEY (CCCD, SoDienThoai),
    CONSTRAINT FK_CCCD FOREIGN KEY (CCCD) REFERENCES SinhVien(CCCD)
);

CREATE TABLE NguoiThan (
	SV_CCCD VARCHAR(12) PRIMARY KEY,
    HoVaTen VARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh CHAR CHECK (GioiTinh IN ('Nam', 'Nữ')),
    CONSTRAINT FK_SV_CCCD FOREIGN KEY (SV_CCCD) REFERENCES SinhVien(CCCD)
);

CREATE TABLE DiaChi (
	SV_CCCD VARCHAR(12) NOT NULL,
    UNIQUE(SV_CCCD),
    HoVaTen VARCHAR(50) NOT NULL,
    Tinh VARCHAR(20),
    QuanHuyen VARCHAR(20),
    Phuong VARCHAR(20),
    TenDuong VARCHAR(20),
    SoNha VARCHAR(5),
    CONSTRAINT FK_SV_CCCD FOREIGN KEY (SV_CCCD) REFERENCES NguoiThan(SV_CCCD),
    CONSTRAINT FK_HoVaTen FOREIGN KEY (HoVaTen) REFERENCES NguoiThan(HoVaTen)
);

CREATE TABLE TaiKhoan (
	TenTaiKhoan VARCHAR(255) PRIMARY KEY,
	MatKhau VARCHAR(255) DEFAULT NULL,
    CCCD VARCHAR(12) NOT NULL,
    UNIQUE (CCCD),
    CONSTRAINT FK_CCCD FOREIGN KEY (CCCD) REFERENCES SinhVien(CCCD)
);

CREATE TABLE NhanVien (
    MaNV VARCHAR(6) PRIMARY KEY CHECK (MaNV REGEXP '^(VP|HT)[0-9]{4}$'),
	TienLuong VARCHAR(10) NOT NULL,
    CCCD VARCHAR(12) NOT NULL,
    UNIQUE (CCCD),

    HoTen VARCHAR(50) NOT NULL,
    GioiTinh CHAR CHECK (GioiTinh IN ('Nam', 'Nữ')),
    NgaySinh DATE NOT NULL
);

CREATE TABLE TruongCumNha (
	MaNV VARCHAR(6) CHECK (MaNV REGEXP '^(TC)[0-9]{4}$'),
    PRIMARY KEY (MaNV),
    Email VARCHAR(50),
    TenCN VARCHAR(20) NOT NULL,
    NgayBatDauQuanLy DATE NOT NULL,
    CONSTRAINT FK_MaNV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE,
    CONSTRAINT FK_TenCN FOREIGN KEY (TenCN) REFERENCES CumNha(TenCN) ON DELETE CASCADE
);

CREATE TABLE TruongToaNha (
	MaNV VARCHAR(6) CHECK (MaNV REGEXP '^(TT)[0-9]{4}$'),
    PRIMARY KEY (MaNV),
    Email VARCHAR(50),
    TenTN VARCHAR(20) NOT NULL,
    NgayBatDauQuanLy DATE NOT NULL,
    CONSTRAINT FK_MaNV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE,
    CONSTRAINT FK_TenTN FOREIGN KEY (TenTN) REFERENCES ToaNha(TenTN) ON DELETE CASCADE
);

CREATE TABLE BaoVe (
	MaNV VARCHAR(6) PRIMARY KEY CHECK (MaNV REGEXP '^(BV)[0-9]{4}$'),
    PRIMARY KEY (MaNV),
    TenCN VARCHAR(20) NOT NULL,
    CONSTRAINT FK_MaNV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE,
    CONSTRAINT FK_TenCN FOREIGN KEY (TenCN) REFERENCES CumNha(TenCN) ON DELETE CASCADE
);

CREATE TABLE TapVu (
    MaNV VARCHAR(6) PRIMARY KEY CHECK (MaNV REGEXP '^(TV)[0-9]{4}$'),
    PRIMARY KEY (MaNV),
    TenTN VARCHAR(20) NOT NULL,
    CONSTRAINT FK_MaNV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE,
    CONSTRAINT FK_TenTN FOREIGN KEY (TenTN) REFERENCES ToaNha(TenTN) ON DELETE CASCADE
);

CREATE TABLE KyThuat (
    MaNV VARCHAR(6) PRIMARY KEY CHECK (MaNV REGEXP '^(KT)[0-9]{4}$'),
    PRIMARY KEY (MaNV),
    LoaiKyThuat VARCHAR(20),
    TenCN VARCHAR(20) NOT NULL,
    CONSTRAINT FK_MaNV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE,
    CONSTRAINT FK_TenCN FOREIGN KEY (TenCN) REFERENCES CumNha(TenCN) ON DELETE CASCADE
);

CREATE TABLE SoDienThoaiNV (
	MaNV VARCHAR(6),
    SoDienThoai VARCHAR(10),
    CONSTRAINT FK_MaNV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
);

CREATE TABLE MatBangDichVu (
	MaMB VARCHAR(6) PRIMARY KEY,
    LoaiDichVu VARCHAR(20) NOT NULL,
    ViTri VARCHAR(20) NOT NULL,
    DienTich INT,
    MaHopDong VARCHAR(6) NOT NULL,
    TenCN VARCHAR(20) NOT NULL,
    MaNV VARCHAR(6) CHECK (MaNV REGEXP '^(TC)[0-9]{4}$'),
    CONSTRAINT FK_MaHopDong FOREIGN KEY (MaHopDong) REFERENCES HopDong(MaHopDong) ON DELETE CASCADE,
    CONSTRAINT FK_TenCN FOREIGN KEY (TenCN) REFERENCES CumNha(TenCN) ON DELETE CASCADE,
    CONSTRAINT FK_MaNV FOREIGN KEY (MaNV) REFERENCES TruongCumNha(MaNV) ON DELETE CASCADE
);

CREATE TABLE CoSoVatChat (
	TenCSVC VARCHAR(50) PRIMARY KEY,
    ViTri VARCHAR(20) NOT NULL,
    GiaThue VARCHAR(10) NOT NULL,
    GioMoCua TIME,
    GioDongCua TIME,
    TenCN VARCHAR(20) NOT NULL,
    MaNV VARCHAR(6) CHECK (MaNV REGEXP '^(TC)[0-9]{4}$'),
    CONSTRAINT FK_TenCN FOREIGN KEY (TenCN) REFERENCES CumNha(TenCN) ON DELETE CASCADE,
    CONSTRAINT FK_MaNV FOREIGN KEY (MaNV) REFERENCES TruongCumNha(MaNV) ON DELETE CASCADE
);

CREATE TABLE NguoiThueMatBang (
	CCCD VARCHAR(12) PRIMARY KEY,
    HoVaTen VARCHAR(50) NOT NULL,
    SoDienThoai VARCHAR(10)
);

CREATE TABLE HopDong (
	MaHopDong VARCHAR(6) PRIMARY KEY,
    MaMB VARCHAR(6) NOT NULL,
    NgayBatDau DATE,
    NgayKetThuc DATE,
    CCCD VARCHAR(12) NOT NULL,
    UNIQUE(CCCD),
    CONSTRAINT FK_CCCD FOREIGN KEY (CCCD) REFERENCES NguoiThueMatBang(CCCD) ON DELETE CASCADE,
	CONSTRAINT FK_MaMB FOREIGN KEY (MaMB) REFERENCES MatBangDichVu(MaMB) ON DELETE CASCADE
);

CREATE TABLE PhieuDangKy (
    MaPDK VARCHAR(6) PRIMARY KEY,
    NgayDK DATE,
    ThoiGianBatDau DATETIME NOT NULL,
    ThoiGianKetThuc DATETIME NOT NULL,
    TenTaiKhoan VARCHAR(255) PRIMARY KEY,
    CONSTRAINT FK_TenTaiKhoan FOREIGN KEY (TenTaiKhoan) REFERENCES TaiKhoan(TenTaiKhoan) ON DELETE CASCADE
);

CREATE TABLE PhieuDangKyLuuTru (
	MaPDK VARCHAR(6) PRIMARY KEY,
    LoaiPhong ENUM('DV', 'KDV'),
    MaHD VARCHAR(20) NOT NULL,
    TenTN VARCHAR(20) NOT NULL,
    SoPhong INT,
    TenTaiKhoan VARCHAR(255),
    CONSTRAINT FK_MaPDK FOREIGN KEY (MaPDK) REFERENCES PhieuDangKy(MaPDK) ON DELETE CASCADE,
    CONSTRAINT FK_MaHD FOREIGN KEY (MaHD) REFERENCES HoaDonLuuTru(MaHD) ON DELETE CASCADE,
    CONSTRAINT FK_TenTaiKhoan FOREIGN KEY (TenTaiKhoan) REFERENCES TaiKhoan(TenTaiKhoan) ON DELETE CASCADE
);

CREATE TABLE PhieuDangKyCSVC (
	MaPDK VARCHAR(6) PRIMARY KEY,
    LoaiCSVC VARCHAR(20) NOT NULL,
    SoGioThue FLOAT,
    DiaDiem VARCHAR(50),
    TenTaiKhoan VARCHAR(255),
    TenCSVC VARCHAR(50) NOT NULL,
    CONSTRAINT FK_MaPDK FOREIGN KEY (MaPDK) REFERENCES PhieuDangKy(MaPDK) ON DELETE CASCADE,
    CONSTRAINT FK_TenTaiKhoan FOREIGN KEY (TenTaiKhoan) REFERENCES TaiKhoan(TenTaiKhoan) ON DELETE CASCADE,
    CONSTRAINT FK_TenCSVC FOREIGN KEY (TenCSVC) REFERENCES CoSoVatChat(TenCSVC) ON DELETE CASCADE
);

CREATE TABLE PhieuDangKyNoiThat (
	MaPDK VARCHAR(6) PRIMARY KEY,
    LoaiPhong ENUM('DV', 'KDV'),
    TenTaiKhoan VARCHAR(255),
    CONSTRAINT FK_MaPDK FOREIGN KEY (MaPDK) REFERENCES PhieuDangKy(MaPDK) ON DELETE CASCADE,
    CONSTRAINT FK_TenTaiKhoan FOREIGN KEY (TenTaiKhoan) REFERENCES TaiKhoan(TenTaiKhoan) ON DELETE CASCADE
);

CREATE TABLE HoaDon (
	MaHD VARCHAR(6) PRIMARY KEY,
    NguoiThanhToan VARCHAR(50) NOT NULL,
    NgayTaoHoaDon DATE,
    LoaiDV VARCHAR(50) NOT NULL,
    NgayDangKy DATE NOT NULL,
    NgayBatDauSD DATE,
    NgayNgungSD DATE,
    HanThanhToan DATE NOT NULL,
    TrangThaiThanhToan TINYINT DEFAULT 0
);

CREATE TABLE HoaDonDienNuoc (
	MaHD VARCHAR(6) PRIMARY KEY,
    ChiSoDienDau FLOAT NOT NULL,
    ChiSoDienCuoi FLOAT NOT NULL,
    Gia1ChiSoDien INT NOT NULL,
    
    ChiSoNuocDau FLOAT NOT NULL,
    ChiSoNuocCuoi FLOAT NOT NULL,
    Gia1ChiSoNuoc INT NOT NULL,
    
    NgayChotChi DATE,
	TenTaiKhoan VARCHAR(255),
    ThangThanhToan INT,
    
    CONSTRAINT FK_MaHD FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ON DELETE CASCADE,
	CONSTRAINT FK_TenTaiKhoan FOREIGN KEY (TenTaiKhoan) REFERENCES TaiKhoan(TenTaiKhoan) ON DELETE CASCADE
);

CREATE TABLE HoaDonNoiThat (
	MaHD VARCHAR(6) PRIMARY KEY,
    GiaThueTheoThang INT NOT NULL,
    MaPDK VARCHAR(6) NOT NULL,
    NamThanhToan INT,
    CONSTRAINT FK_MaHD FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ON DELETE CASCADE,
    CONSTRAINT FK_MaPDK FOREIGN KEY (MaPDK) REFERENCES PhieuDangKyNoiThat(MaPDK) ON DELETE CASCADE
);

CREATE TABLE HoaDonCSVC (
	MaHD VARCHAR(6) PRIMARY KEY,
    LoaiCSVC VARCHAR(20) NOT NULL,
    DiaDiem VARCHAR(50),
    GiaThue1Gio INT NOT NULL,
    SoGioThue FLOAT,
    TenCSVC VARCHAR(50) NOT NULL,
    MaPDK VARCHAR(6) NOT NULL,
    CONSTRAINT FK_MaHD FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ON DELETE CASCADE,
    CONSTRAINT FK_MaPDK FOREIGN KEY (MaPDK) REFERENCES PhieuDangKyNoiThat(MaPDK) ON DELETE CASCADE
);

CREATE TABLE HoaDonLuuTru (
	MaHD VARCHAR(6) PRIMARY KEY,
    LoaiPhong ENUM('DV', 'KDV'),
    GiaLuuTru1Thang INT NOT NULL,
    CONSTRAINT FK_MaHD FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ON DELETE CASCADE
);

CREATE TABLE HoaDonThueMBDV (
	MaHD VARCHAR(20),
    MaMB VARCHAR(20),
    PRIMARY KEY (MaHD, MaMB),
    DienTich INT,
    ViTri VARCHAR(20) NOT NULL,
    GiaThue VARCHAR(10) NOT NULL,
    MaHopDong VARCHAR(6) NOT NULL,
    CONSTRAINT FK_MaHD FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ON DELETE CASCADE,
	CONSTRAINT FK_MaHopDong FOREIGN KEY (MaHopDong) REFERENCES HopDong(MaHopDong) ON DELETE CASCADE
);